name: sinfo
description: Pantheon hosted website information gatherer.
version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.6.0
  console: ^3.1.0
  path: ^1.7.0

dev_dependencies:
  effective_dart: ^1.3.0
  test: ^1.14.4
  flutter_test:
    sdk: flutter
