name: sinfo
description: Pantheon hosted website information gatherer.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.2
  console: ^4.1.0
  http: ^0.13.5
  intl: ^0.18.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
